##Installation of Cluster Manager (Kubernetes/k3s) with one master node and two worker nodes as well as  docker, and all the dependencies
---

- name: Install and configure K3s cluster
  hosts: master,workers
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Get home directory of the user
      shell: "getent passwd {{ ansible_user }} | cut -d: -f6"
      register: user_home

    - name: Print home directory
      debug:
        var: user_home.stdout




- name: Configure all Kubernetes nodes to send data to sFlow-RT collector
  hosts: master
  tasks:
    - name: Create host-sflow.yml file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../../host-sflow.yml.j2"
        dest: "{{ user_home.stdout }}/host-sflow.yml"
      vars:
        user_home: "{{ lookup('env', 'HOME') }}"

    - name: Deploy host-sflow.yml file
      shell: kubectl apply -f host-sflow.yml
      become: yes



    - name: Create deployment.yml file
      ansible.builtin.template:
        src: deployment.yml.j2
        dest: "{{ user_home.stdout }}/deployment.yml"
      vars:
        user_home: "{{ lookup('env', 'HOME') }}"

    - name: Deploy deployment.yml file
      shell: kubectl apply -f  deployment.yml
      become: yes



    - name: Retrieve IP address of tap0 in worker1 node
      set_fact:
        tap0_ip_worker1: "{{ groups['worker1_tap0'][0] }}"


    - name: Split tap0 ip address from the subnet mask to extract IP address
      set_fact:
        tap0_ip_address_worker1: "{{ tap0_ip_worker1.split('/')[0] }}"

    - name: Execute ping command
      shell: ping -c 2 {{tap0_ip_address_worker1}}
